name: Qlik Hub Changelog Watcher

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 09:00 UTC
  workflow_dispatch:

jobs:
  check-hub-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies (Playwright)
      run: |
        pip install requests playwright
        playwright install

    - name: Run changelog script
      env:
        GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
      run: python check_qlik_hub_changelog.py

    - name: Commit updated last_seen_titles.txt to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add last_seen_titles.txt
        git commit -m "Update last_seen_titles.txt [bot]" || echo "No changes to commit"
        git push

